import type { Invoice } from "./types";

// Default document = the Kanthiveda Herbals e-commerce quotation.
// Everything here is editable at runtime; this is just the starting point.
export const defaultInvoice: Invoice = {
  meta: {
    accent: "#005EF9",
    docNoLabel: "Quotation No.",
    docNo: "BMC-KVH-2026-001",
    dateLabel: "Date of Issue",
    date: "15 July 2026",
    currency: "₹",
    brandFooter: "Blue Moon Creatives",
    docFooter: "E-Commerce Website — Kanthiveda Herbals",
  },
  brand: {
    logo: "/logo.png",
    name: "Blue Moon Creatives",
    tagline: "Design & Development Studio",
  },
  cover: {
    eyebrow: "Website Quotation",
    titleA: "E-Commerce",
    titleB: "Website",
    sub: "Design & Development · Full Online Storefront",
  },
  provider: {
    label: "Prepared By",
    name: "Blue Moon Creatives",
    lines: ["Pratik Das — Senior Developer & Co-Founder", "+91 8240621055 · +91 9477105828"],
  },
  client: {
    label: "Billed To",
    name: "Kanthiveda Herbals",
    lines: ["Kanthamani · Belagavi", "9035671973", "Kanthivedaherbals@gmail.com"],
  },
  invest: {
    title: "Investment Summary",
    note: "Amounts in INR (₹)",
    items: [
      {
        name: "Website Design",
        desc: "UI/UX, layout & visual system across all pages",
        qty: "5 pages",
        unit: "Mixed",
        amount: 5000,
      },
      {
        name: "Website Development",
        desc: "Full-stack build, storefront + admin panel",
        qty: "5 pages",
        unit: "Mixed",
        amount: 20000,
      },
    ],
    totalLabel: "Total Project Fee",
    totalNote: "Initial payment 50% · balance on delivery",
    advancePct: 50,
  },
  scope: {
    enabled: true,
    num: "01",
    title: "Scope of Work",
    lead: "Blue Moon Creatives will design and develop a complete, production-ready <b>e-commerce website</b> for Kanthiveda Herbals — a full online storefront with home page, shop/product listing, individual product pages, and a full admin dashboard. <b>Domain &amp; hosting are excluded</b> from this scope.",
    deliverables: [
      {
        idx: "DELIVERABLE 01",
        price: "₹5,000",
        name: "Website Design",
        meta: "5 Pages · Mixed",
        desc: "End-to-end interface design covering the customer storefront and admin experience, built as a consistent, responsive visual system.",
        includes: [
          "Home, shop & product page layouts",
          "Checkout & account flows",
          "Responsive, mobile-first design",
          "Custom page content & write-ups",
        ],
      },
      {
        idx: "DELIVERABLE 02",
        price: "₹20,000",
        name: "Website Development",
        meta: "5 Pages · Mixed",
        desc: "Full-stack implementation of the storefront, secure checkout, customer accounts, and a complete admin management panel.",
        includes: [
          "Storefront + secure checkout",
          "Razorpay & Cash-on-Delivery payments",
          "Full admin dashboard",
          "Delhivery shipment integration",
        ],
      },
    ],
    note: "<b>What's included —</b> Custom page content/write-ups are covered within the quoted price. Free third-party integrations relevant to the website are implemented once, as defined in the approved scope. <b>Not included —</b> domain registration, indexing, and paid third-party services/tools.",
  },
  features: {
    enabled: true,
    num: "02",
    title: "Feature Summary",
    lead: "A complete feature set spanning the customer-facing storefront and the admin control panel — <b>42 features</b> in total, grouped below for clarity.",
    groups: [
      {
        tag: "Storefront",
        title: "Customer Experience",
        range: "01–22",
        items: [
          { title: "Full E-Commerce Store", desc: "Home, shop/product listing & individual product pages." },
          { title: "Filtering & Sorting", desc: "By category, colour, size, price range; sort by price/name/newest." },
          { title: "Site-wide Search", desc: "Instant, fuzzy product and page matching." },
          { title: "Rich Product Pages", desc: "Multiple images, colour/size selection, size-guide chart." },
          { title: "Shopping Cart", desc: "Drawer + full page, quantity controls, persistent across visits." },
          { title: "Multi-step Checkout", desc: "Address entry, saved-address autofill, coupon code support." },
          { title: "Flexible Payments", desc: "Cash on Delivery or Razorpay — full, 30% or 50% partial." },
          { title: "Server-side Verification", desc: "Totals & payment signatures re-checked to prevent tampering." },
          { title: "Customer Accounts", desc: 'Email/password login and "Sign in with Google".' },
          { title: "Two-factor Login", desc: "Password plus a one-time email code for added security." },
          { title: "Email Verification", desc: "Verify on signup with an automatic welcome email." },
          { title: "Password Recovery", desc: "Forgot-password flow via emailed one-time code." },
          { title: "Set / Change Password", desc: "Even for accounts that originally signed up with Google." },
          { title: "Guest Order Linking", desc: "Guest orders auto-linked once the email is verified." },
          { title: "Profile Management", desc: "Name, phone, avatar photo & saved shipping address." },
          { title: "Order History", desc: "Detailed view, live tracking timeline, PDF invoices." },
          { title: "Product Reviews", desc: "Star ratings, written feedback & rating distribution." },
          { title: "Marketing Homepage", desc: "Hero slider, bestsellers, categories, testimonials, FAQ." },
          { title: "Core Content Pages", desc: "About, Contact, Privacy Policy & Terms." },
          { title: "Support Tickets", desc: "Contact form creates a trackable ticket + auto emails." },
          { title: "SEO Ready", desc: "Auto-generated sitemap & social share previews." },
          { title: "Fast & Smooth", desc: "Animated transitions, lazy-loading, optimized images." },
        ],
      },
      {
        tag: "Admin",
        title: "Management & System",
        range: "23–42",
        items: [
          { title: "Admin Dashboard", desc: "Sales overview, order status breakdown, monthly chart." },
          { title: "Product Management", desc: "Add/edit/delete with rich text, images, pricing." },
          { title: "Variant Management", desc: "Colours, sizes & per-variant pricing/images/SKUs." },
          { title: "Category Management", desc: "Organise the catalogue into categories." },
          { title: "Size-guide Builder", desc: "Custom size charts per product type." },
          { title: "Coupon Management", desc: "Percentage discount, minimum spend, expiry date." },
          { title: "Curated Collections", desc: "Hand-pick & reorder Bestsellers / Freshly Arrived." },
          { title: "Order Management", desc: "Update status with automatic customer email alerts." },
          { title: "Shipment Tracking", desc: "Delhivery — create shipments, track AWB, daily sync." },
          { title: "Customer List", desc: "Manage the full customer base." },
          { title: "Review Moderation", desc: "View and remove product reviews." },
          { title: "Testimonials", desc: "Curate homepage customer quotes." },
          { title: "Media Library", desc: "Drag-and-drop uploads, reusable across content." },
          { title: "Ticket Inbox", desc: "Read/unread tracking with quick email reply." },
          { title: "Recycle Bin", desc: "Recover or permanently delete removed items." },
          { title: "Global Admin Search", desc: "Jump to any section of the admin panel." },
          { title: "Light / Dark Theme", desc: "Theme support across the admin panel." },
          { title: "Role-based Access", desc: "Staff vs. customer permissions on every request." },
          { title: "Transactional Emails", desc: "Orders, OTPs, alerts, verification & confirmations." },
          { title: "Secure Infrastructure", desc: "Encrypted sessions, security headers, safe uploads." },
        ],
      },
    ],
  },
  terms: {
    enabled: true,
    num: "03",
    title: "Terms & Milestones",
    items: [
      "<b>50% advance payment</b> is required prior to the commencement of the project. The remaining balance is payable as per the agreed milestones or final delivery terms.",
      "<b>Additional revisions or changes</b> beyond the agreed scope may be subject to extra charges.",
      "<b>Domain registration, indexing and paid third-party services/tools</b> are not included. Free third-party integrations are implemented once, as defined within the approved scope.",
      "<b>Custom page content/write-ups</b> are included within the quoted pricing. On successful completion and receipt of final payment, the complete <b>source code and all project files</b> are handed over to the client.",
    ],
    mileTag: "Milestones",
    mileTitle: "Payment Schedule",
    milestones: [
      {
        n: "1",
        title: "Initial Advance",
        pct: "50%",
        desc: "Payable as an initial advance prior to the commencement of the project.",
      },
      {
        n: "2",
        title: "Final Balance",
        pct: "50%",
        desc: "Payable on successful completion, final approval and an end-to-end demo. Project files & source code are handed over after the balance is settled.",
      },
    ],
    stats: [
      { k: "Total Fee", v: "₹25,000", sub: "Design + Development" },
      { k: "Advance Due", v: "₹12,500", sub: "50% before commencement" },
      { k: "Timeline", v: "35–40 <small>Days</small>", sub: "Approximate delivery" },
    ],
  },
  requirements: {
    enabled: true,
    num: "04",
    title: "Initial Requirements",
    lead: "To begin work smoothly and keep to the estimated timeline, please have the following ready to share at kick-off.",
    items: [
      {
        letter: "A",
        title: "Brand & Business",
        html: "Brand name, <span>logo</span>, About Us content, contact information (phone, email, address), social media links, and typography/colour palette preferences (if any).",
      },
      {
        letter: "B",
        title: "Products",
        html: "All product <span>visuals</span>, categories & subcategories, product descriptions, pricing, and product variations (if any).",
      },
      {
        letter: "C",
        title: "Payment & Orders",
        html: "<span>Bank account details</span> for the payment gateway, and GST details (if applicable).",
      },
      {
        letter: "D",
        title: "Technical Access",
        html: "<span>Domain & hosting access</span>, plus a spare Gmail account for service configuration.",
      },
    ],
    note: "<b>Timely inputs keep us on schedule.</b> The estimated <b>35–40 day</b> timeline assumes required materials, feedback and approvals are provided promptly at each stage.",
  },
  payment: {
    enabled: true,
    num: "05",
    title: "Payment Details",
    bankLabel: "Bank Transfer",
    bank: [
      { k: "Account Name", v: "Pratik Das" },
      { k: "Account Number", v: "015699500019202" },
      { k: "IFSC Code", v: "YESB0000565" },
      { k: "UPI ID", v: "pr4t1kdas-2@okicici" },
    ],
    contactLabel: "Contact",
    personName: "Pratik Das",
    personRole: "Senior Developer & Co-Founder",
    contact: [
      { k: "Phone", v: "+91 8240621055" },
      { k: "Alt. Phone", v: "+91 9477105828" },
      { k: "Studio", v: "Blue Moon Creatives" },
    ],
    signTag: "Sign-off",
    signTitle: "Agreement & Acceptance",
    signLead:
      "Acceptance of this quotation confirms agreement with the scope, pricing and terms set out in this document.",
    signs: [
      { name: "Blue Moon Creatives", role: "Service Provider" },
      { name: "Kanthiveda Herbals", role: "Client · Authorised Representative" },
    ],
    thanksA: "Thank you for choosing",
    thanksB: "Blue Moon Creatives",
    thanksSub: "We look forward to building something exceptional together.",
  },
};
